# Generated by Django 5.1.7 on 2025-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=30)),
                ('Emp_salary', models.IntegerField()),
                ('Emp_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
